--liquibase formatted sql
--changeset sibvibe:14-001-organizations dbms:postgresql

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    max_user_id BIGINT NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_app_user_max_user UNIQUE (max_user_id)
);

CREATE TABLE organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    inn VARCHAR(255),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_demo BOOLEAN NOT NULL,
    demo_owner_id BIGINT,
    CONSTRAINT fk_org_creator FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT fk_org_demo_owner FOREIGN KEY (demo_owner_id) REFERENCES app_user(id),
    CONSTRAINT uq_org_id_demo UNIQUE (id, is_demo),
    CONSTRAINT ck_org_demo_owner CHECK ((is_demo AND demo_owner_id IS NOT NULL) OR (NOT is_demo AND demo_owner_id IS NULL))
);

-- is_demo дублируется только для partial index; составной FK исключает рассинхрон.
CREATE TABLE organization_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    is_admin BOOLEAN NOT NULL,
    joined_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_demo BOOLEAN NOT NULL,
    CONSTRAINT fk_member_org_demo FOREIGN KEY (org_id, is_demo) REFERENCES organization(id, is_demo),
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uq_member_org_user UNIQUE (org_id, user_id),
    CONSTRAINT ck_organization_member_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT fk_role_org FOREIGN KEY (org_id) REFERENCES organization(id),
    CONSTRAINT uq_role_org_code UNIQUE (org_id, code),
    CONSTRAINT uq_role_id_org UNIQUE (id, org_id)
);

CREATE TABLE member_role (
    member_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    granted_by BIGINT NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (member_id, role_id),
    CONSTRAINT fk_member_role_member FOREIGN KEY (member_id) REFERENCES organization_member(id),
    CONSTRAINT fk_member_role_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT fk_member_role_granter FOREIGN KEY (granted_by) REFERENCES app_user(id)
);

CREATE TABLE invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    code VARCHAR(255),
    token VARCHAR(255),
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    used_at TIMESTAMP WITH TIME ZONE,
    used_by BIGINT,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_invite_org FOREIGN KEY (org_id) REFERENCES organization(id),
    CONSTRAINT fk_invite_creator FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT fk_invite_user FOREIGN KEY (used_by) REFERENCES app_user(id),
    CONSTRAINT uq_invite_token UNIQUE (token),
    CONSTRAINT uq_invite_code UNIQUE (code),
    CONSTRAINT uq_invite_id_org UNIQUE (id, org_id),
    CONSTRAINT ck_invite_kind_fields CHECK ((kind = 'ORG_CODE' AND code IS NOT NULL AND token IS NULL AND expires_at IS NULL AND used_at IS NULL AND used_by IS NULL) OR (kind = 'PERSONAL_LINK' AND code IS NULL AND token IS NOT NULL AND expires_at IS NOT NULL)),
    CONSTRAINT ck_invite_used CHECK ((used_at IS NULL) = (used_by IS NULL)),
    CONSTRAINT ck_invite_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT ck_invite_kind CHECK (kind IN ('ORG_CODE', 'PERSONAL_LINK'))
);

CREATE TABLE invite_role (
    invite_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (invite_id, role_id),
    CONSTRAINT fk_invite_role_invite FOREIGN KEY (invite_id) REFERENCES invite(id),
    CONSTRAINT fk_invite_role_role FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE join_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    invite_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    decided_by BIGINT,
    decided_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_join_org FOREIGN KEY (org_id) REFERENCES organization(id),
    CONSTRAINT fk_join_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_join_invite_org FOREIGN KEY (invite_id, org_id) REFERENCES invite(id, org_id),
    CONSTRAINT fk_join_decider FOREIGN KEY (decided_by) REFERENCES app_user(id),
    CONSTRAINT ck_join_request_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
