--liquibase formatted sql
--changeset sibvibe:14-002-types-rules dbms:postgresql

CREATE TABLE document_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(255) NOT NULL,
    is_generic BOOLEAN NOT NULL,
    CONSTRAINT uq_document_type_code UNIQUE (code)
);

CREATE TABLE document_type_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id BIGINT NOT NULL,
    field_name VARCHAR(255) NOT NULL,
    field_type VARCHAR(32) NOT NULL,
    label VARCHAR(255) NOT NULL,
    hint TEXT,
    CONSTRAINT fk_type_field_type FOREIGN KEY (document_type_id) REFERENCES document_type(id),
    CONSTRAINT uq_type_field_name UNIQUE (document_type_id, field_name),
    CONSTRAINT ck_document_type_field_field_type CHECK (field_type IN ('STRING', 'DATE', 'NUMBER', 'PERSON', 'ORGANIZATION'))
);

CREATE TABLE requirement_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id BIGINT NOT NULL,
    field_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    check_type VARCHAR(32) NOT NULL,
    expected TEXT,
    kind VARCHAR(32) NOT NULL,
    severity VARCHAR(32) NOT NULL,
    source_title TEXT NOT NULL,
    source_url TEXT,
    source_ref TEXT,
    source_checked_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_rule_document_type_field FOREIGN KEY (document_type_id, field_name)
        REFERENCES document_type_field(document_type_id, field_name),
    CONSTRAINT ck_requirement_rule_check_type CHECK (check_type IN ('REQUIRED', 'DATE_FORMAT', 'DATE_NOT_FUTURE', 'MATCHES_PATTERN', 'MIN_LENGTH', 'ONE_OF')),
    CONSTRAINT ck_requirement_rule_kind CHECK (kind IN ('LEGAL', 'INTERNAL_POLICY', 'PRODUCT_RULE')),
    CONSTRAINT ck_requirement_rule_severity CHECK (severity IN ('BLOCKER', 'WARNING', 'INFO'))
);
