--liquibase formatted sql
--changeset sibvibe:14-003-documents dbms:postgresql

CREATE TABLE document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_stage INTEGER,
    current_version_no INTEGER NOT NULL,
    visibility VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_document_type FOREIGN KEY (document_type_id) REFERENCES document_type(id),
    CONSTRAINT fk_document_author FOREIGN KEY (author_id) REFERENCES app_user(id),
    CONSTRAINT fk_document_org FOREIGN KEY (org_id) REFERENCES organization(id),
    CONSTRAINT ck_document_version CHECK (current_version_no > 0),
    CONSTRAINT ck_document_stage CHECK (current_stage IS NULL OR current_stage > 0),
    CONSTRAINT ck_document_status CHECK (status IN ('DRAFT', 'IN_APPROVAL', 'APPROVED', 'RETURNED', 'REJECTED')),
    CONSTRAINT ck_document_visibility CHECK (visibility IN ('PRIVATE', 'ORG'))
);

CREATE TABLE document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    contains_sensitive BOOLEAN NOT NULL,
    content JSONB,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    extracted_fields JSONB,
    validation_issues JSONB,
    check_status VARCHAR(255),
    CONSTRAINT fk_version_document FOREIGN KEY (document_id) REFERENCES document(id),
    CONSTRAINT fk_version_creator FOREIGN KEY (created_by) REFERENCES app_user(id),
    CONSTRAINT uq_version_number UNIQUE (document_id, version_no),
    CONSTRAINT ck_version_number CHECK (version_no > 0),
    CONSTRAINT ck_version_check_status CHECK (check_status IN ('CHECKED', 'FAILED'))
);

CREATE TABLE document_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    position INTEGER NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    file_name TEXT NOT NULL,
    mime_type VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_file_version FOREIGN KEY (version_id) REFERENCES document_version(id),
    CONSTRAINT uq_file_position UNIQUE (version_id, position),
    CONSTRAINT ck_file_position CHECK (position >= 0),
    CONSTRAINT ck_file_size CHECK (file_size >= 0),
    CONSTRAINT ck_document_file_kind CHECK (kind IN ('MAIN', 'ATTACHMENT'))
);
