--liquibase formatted sql
--changeset sibvibe:14-004-approval dbms:postgresql

CREATE TABLE approval_route (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type_id BIGINT NOT NULL,
    org_id BIGINT NOT NULL,
    stage_order INTEGER NOT NULL,
    role_id BIGINT NOT NULL,
    is_mandatory BOOLEAN NOT NULL,
    CONSTRAINT fk_route_type FOREIGN KEY (document_type_id) REFERENCES document_type(id),
    CONSTRAINT fk_route_org FOREIGN KEY (org_id) REFERENCES organization(id),
    CONSTRAINT fk_route_role_org FOREIGN KEY (role_id, org_id) REFERENCES role(id, org_id),
    CONSTRAINT ck_route_stage CHECK (stage_order > 0),
    CONSTRAINT uq_route_stage_role UNIQUE (org_id, document_type_id, stage_order, role_id)
);

CREATE TABLE approval_step (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    approver_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    stage_order INTEGER NOT NULL,
    origin VARCHAR(32) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    auto_reason VARCHAR(32),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    activated_at TIMESTAMP WITH TIME ZONE,
    decided_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_step_version FOREIGN KEY (document_id, version_no) REFERENCES document_version(document_id, version_no),
    CONSTRAINT fk_step_approver FOREIGN KEY (approver_id) REFERENCES app_user(id),
    CONSTRAINT fk_step_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT ck_step_stage CHECK (stage_order > 0),
    CONSTRAINT ck_step_auto_reason_requires_approved CHECK (auto_reason IS NULL OR decision = 'APPROVED'),
    CONSTRAINT ck_approval_step_origin CHECK (origin IN ('TEMPLATE', 'ADDED_BY_AUTHOR')),
    CONSTRAINT ck_approval_step_decision CHECK (decision IN ('PENDING', 'APPROVED', 'RETURNED', 'REJECTED', 'SKIPPED')),
    CONSTRAINT ck_step_auto_reason_value CHECK (auto_reason IS NULL OR auto_reason IN ('AUTHOR_HOLDS_ROLE'))
);
